export default {

	PROFILES_RECEIVED: 'PROFILES_RECEIVED',
	PROFILE_CREATED: 'PROFILE_CREATED',
	PROFILE_SELECTED: 'PROFILE_SELECTED',


	CURRENT_URDER_RECEIVED: 'CURRENT_URDER_RECEIVED',


	BOOKMARKS_RECEIVED: 'BOOKMARKS_RECEIVED',
	BOOKMARK_CREATED: 'BOOKMARK_CREATED',
}