export default {

	API_ROOT: 'http://localhost:3000',

	PROFILES_RECEIVED: 'PROFILES_RECEIVED',
	PROFILE_CREATED: 'PROFILE_CREATED',
	PROFILE_SELECTED: 'PROFILE_SELECTED',


	CURRENT_URDER_RECEIVED: 'CURRENT_URDER_RECEIVED',


	BOOKMARKS_RECEIVED: 'BOOKMARKS_RECEIVED',
	BOOKMARK_CREATED: 'BOOKMARK_CREATED',



	DOC_CREATED: 'DOC_CREATED',
}